CUDA_VISIBLE_DEVICES=0 PYTHONPATH=. python training/train.py \
  --model mlp2 \
  --contextmixer True \
  --optimizer adamwschedulefree \
  --split spectral \
  --seed 42 \
  --lr 1e-2 \
  --wd 0.0 \
  --clr 1e-3 \
  --cwd 1e-5 \
  --dropout 0.2 \
  --num_layers 2 \
  --hidden_dim 32 \
  --batch_size 128 \
  --batchnorm False \
  --outer_episodes 50 \
  --inner_episodes 5 \
  --initialize_weights False \
  --early_stopping_episodes 100
