CUDA_VISIBLE_DEVICES=0 PYTHONPATH=. python main.py \
  --model mlp \
  --mixer_phi False \
  --optimizer adamwschedulefree \
  --split spectral \
  --fingerprint ecfp \
  --seed 42 \
  --lr 1e-2 \
  --wd 0.0 \
  --dropout 0.2 \
  --num_layers 1 \
  --hidden_dim 32 \
  --batch_size 64 \
  --batchnorm True \
  --initialize_weights True \
  --early_stopping_episodes 100
