CUDA_VISIBLE_DEVICES=0 PYTHONPATH=. python main.py \
  --root /c2/jeff/DrugDiscovery/data/ \
  --model mlp \
  --mixer_phi True \
  --optimizer adamw \
  --split spectral \
  --fingerprint ecfp \
  --seed 42 \
  --lr 1e-3 \
  --wd 0.0 \
  --clr 1e-5 \
  --cwd 5e-4 \
  --ln False \
  --dropout 0.5 \
  --num_layers 1 \
  --hidden_dim 32 \
  --batch_size 64 \
  --batchnorm False \
  --outer_episodes 100 \
  --inner_episodes 10 \
  --initialize_weights False \
  --early_stopping_episodes 100
